(()=>{
const EN={
'牛魔王':'Toro','歐米茄':'Omega','美娜':'Mina','薩尼':'Thane','哥德爾':'Gildur','查戈納爾':'Chaugnar','塔拉':'Taara','贊尼爾':'Xeniel','阿杜恩':'Arduin','伯頓':'Baldum','諾可西':'Roxie','古木':"Y'bneth",'維羅':'Wiro','阿塔':'Ata','艾瑞':'Arum',
'渥馬爾':'Ormarr','麥克思':'Max','瑟斐斯':'Zephys','呂布':'Lu Bu','趙雲':'Zanis','馬洛斯':'Maloch','莫托斯':'Arthur','愛里':'Airi','司科德':'Skud','祖卡':'Zuka','超人':'Superman','凱格路士':'Kil’Groth','龍馬':'Ryoma','艾翠絲':'Astrid','神力女超人':'Wonder Woman','夜叉':'Omen','洛克':'Rourke','艾蜜莉':'Amily','瑞克':'Riktor','緋淚':'Veres','弗洛倫':'Florentino','埃羅':'Errol','葉娜':'Yena','筱清':'Qi','安格列':'Volkath','亞連':'Allain','青硯':'Tachi','霧己':'Yan','夜姬':'Dextra',
'刀鋒寶貝':'Butterfly','納克羅斯':'Nakroth','悟空':'Wukong','科里納卡':'Kriknak','蝙蝠俠':'Batman','莫拉':'Murad','奎倫':'Quillen','銀晝':'Enzo','綺蘿':'Keera','潘因':'Paine','颯枷':'Zata','蘇離':'Sinestrea','星葵':'Aoi','布萊特':'Bright','齊爾':'Zill','閃電俠':'The Flash','拉茲':'Raz',
'薇菈':'Veera','阿茲卡':'Azzen’Ka','盧蜜亞':'Ilumia','蘿兒':'Lauriel','貂蟬':'Diaochan','阿萊斯特':'Aleister','克里希':'Krixi','卡莉':'Kahlii','穆加爵':'Mganga','普雷塔':'Preyta','娜塔亞':'Natalya','金納':'Jinnar','伊耿士':'Ignis','圖倫':'Tulen','莉莉安':'Liliana','瑪迦':'Marja','瀾':'Sephera','達爾西':"D'Arcy",'依夏':'Ishar','狄拉克':'Dirak','伊格':'Iggy','洛里昂':'Lorion','令月':'Yue',
'堇':'Violet','勇':'Yorn','凡恩':'Valhein','菲尼克':'Fennik','史蘭茲':'Slimz','特爾安娜絲':"Tel'Annas",'小丑':'The Joker','摩恩':'Moren','琳蒂':'Lindis','靈靈':'Wisp','蘇':'Elsu','亥犽':'Hayate','卡芬妮':'Capheny','希露卡':'Celica','蘭鐸':"Eland'orr",'拉維爾':'Laville','索文':'Thorne','緹莉':'Teeri',
'愛麗絲':'Alice','克萊斯':'Cresht','夸克':'Grakk','朗博':'Lumburr','海倫':'Helen','提米':'TeeMee','安奈特':'Annette','皮皮':'Zip','卡瑞茲':'Krizzix','若伊':'Rouie','芽芽':'Aya'
};
const HP_FALLBACK={'哥德爾':3378};
const DATA_URL='https://raw.githubusercontent.com/MLuc24/lien-quan-data/main/data/heroes.json';
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’' ._-]/g,'')}
function quantile(items){const vals=items.map(x=>x.hp).filter(Number.isFinite).sort((a,b)=>a-b);return items.map(x=>{if(!Number.isFinite(x.hp))return{...x,points:0};const i=d3.bisectLeft(vals,x.hp);return{...x,points:Math.max(1,Math.min(10,Math.floor(i*10/vals.length)+1))}})}
async function loadHP(){const r=await fetch(DATA_URL,{cache:'no-store'});if(!r.ok)throw Error('HP data');const raw=await r.json(),by=new Map();for(const h of raw){const hp=Number((h.stats||[]).find(s=>s.id==='maxhp')?.value);if(!Number.isFinite(hp))continue;[h.name,h.slug].filter(Boolean).forEach(k=>by.set(norm(k),hp))}const items=AOV_HEROES.map(h=>{const en=EN[h.name]||'',hp=by.get(norm(en))??by.get(norm(h.name))??HP_FALLBACK[h.name];return{name:h.name,role:h.role,en,hp}});return quantile(items)}
function addButton(){const card=[...document.querySelectorAll('#home .card')].find(c=>c.querySelector('h2')?.textContent.includes('傳說對決英雄'));if(!card||card.querySelector('.aovHpBtn'))return;let wrap=card.querySelector('.modeBtns');if(!wrap){wrap=document.createElement('div');wrap.className='modeBtns';card.appendChild(wrap);const solo=document.createElement('button');solo.className='singleBtn';solo.textContent='單人';solo.onclick=e=>{e.preventDefault();e.stopPropagation();window.TinaRouter?.go('aov')||(location.hash='aov')};wrap.appendChild(solo)}wrap.style.gridTemplateColumns='1fr 1fr';const b=document.createElement('button');b.className='territoryBtn aovHpBtn';b.textContent='❤️ 血量 PK';b.onclick=e=>{e.preventDefault();e.stopPropagation();window.TinaRouter?.go('aov-hp-pk')||(location.hash='aov-hp-pk')};wrap.appendChild(b)}
async function startAovHpPK(){home.style.display='none';game.style.display='flex';resetUI();map.style.display='none';title.textContent='❤️ 傳說英雄血量 PK';ans.placeholder='輸入英雄名稱';const board=document.createElement('div');board.id='aovHpBoard';board.className='pkBoard';map.parentElement.appendChild(board);board.innerHTML='<div style="text-align:center;padding:40px 10px;color:#68717a">英雄血量資料載入中…</div>';let items;try{items=await loadHP()}catch(e){board.innerHTML='<div class="bad" style="padding:20px">英雄血量資料載入失敗，請重新整理再試。</div>';go.disabled=finish.disabled=true;return}const missingData=items.filter(x=>!x.points),valid=items.filter(x=>x.points),lookup=new Map(valid.map(x=>[N(x.name),x])),used=new Set(),scores=[0,0],turn=0,passes=0,done=false,history=[];let submitting=false;total.textContent=valid.length;n.textContent='0';
function render(){board.innerHTML=`<div class="pkPlayers"><div class="pkPlayer ${turn===0&&!done?'active':''}"><b>玩家 1</b><div class="pkScore">${scores[0]} 分</div></div><div class="pkVs">VS</div><div class="pkPlayer ${turn===1&&!done?'active':''}"><b>玩家 2</b><div class="pkScore">${scores[1]} 分</div></div></div><div class="pkRule">輪流輸入英雄名稱來佔領英雄。以 Lv.1 裸裝基礎生命值分成 10 個級距，血量越高分數越高（1～10 分）。同一英雄只能被佔領一次；連續兩次 Pass 或公布答案即結束。</div><button class="territoryPass" id="aovHpPass" ${done?'disabled':''}>Pass</button><div class="territoryLegend"><span>玩家 1：${scores[0]} 分</span><span>玩家 2：${scores[1]} 分</span></div><div class="pkHistory">${history.slice().reverse().map(h=>`<div class="pkLog ${h.ok?'ok':'bad'}">${h.text}</div>`).join('')}</div>`;board.querySelector('#aovHpPass')?.addEventListener('click',pass)}
function say(t,ok){msg.innerHTML=`<span class="${ok?'ok':'bad'}">${t}</span>`}
function submit(){if(done||submitting)return;const raw=ans.value.trim();if(!raw)return;submitting=true;ans.value='';const x=lookup.get(N(raw));if(!x){say('沒有找到可計分的英雄。',false);submitting=false;ans.focus();return}if(used.has(x.name)){say(x.name+' 已經被佔領。',false);submitting=false;ans.focus();return}used.add(x.name);scores[turn]+=x.points;history.push({ok:true,text:`玩家 ${turn+1}｜${x.name}｜基礎生命 ${x.hp}｜+${x.points} 分`});n.textContent=used.size;passes=0;turn=1-turn;say(`✓ ${x.name}：${x.hp} HP，${x.points} 分`,true);render();requestAnimationFrame(()=>{submitting=false;ans.focus()})}
function pass(){if(done||submitting)return;history.push({ok:false,text:`玩家 ${turn+1} Pass`});passes++;turn=1-turn;if(passes>=2){end(false);return}render();ans.focus()}
function end(reveal=true){if(done)return;done=true;go.disabled=finish.disabled=true;const winner=scores[0]===scores[1]?'平手':scores[0]>scores[1]?'玩家 1 勝利':'玩家 2 勝利';missing.style.display='block';const left=valid.filter(x=>!used.has(x.name)).sort((a,b)=>b.hp-a.hp);missing.innerHTML=`<b>${winner}｜${scores[0]} : ${scores[1]}</b><br>已佔領 ${used.size}/${valid.length}`+(reveal?`<br><br><b>未佔領英雄（血量／分數）</b><br>${left.map(x=>`${x.name} ${x.hp} HP（${x.points}分）`).join('、')}`:'')+(missingData.length?`<br><br>無可用血量資料、不計分：${missingData.map(x=>x.name).join('、')}`:'');render();window.TinaGuard?.markFinished?.()}
go.onclick=submit;finish.textContent='公布答案';finish.onclick=()=>end(true);ans.onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();submit()}};render();ans.focus()}
window.startAovHpPK=startAovHpPK;window.addEventListener('DOMContentLoaded',addButton);if(document.readyState!=='loading')addButton();
})();