(()=>{
const EN={
'牛魔王':'Toro','歐米茄':'Omega','美娜':'Mina','薩尼':'Thane','哥德爾':'Gildur','查戈納爾':'Chaugnar','塔拉':'Taara','贊尼爾':'Xeniel','阿杜恩':'Arduin','伯頓':'Baldum','諾可西':'Roxie','古木':"Y'bneth",'維羅':'Wiro','阿塔':'Ata','艾瑞':'Arum',
'渥馬爾':'Ormarr','麥克思':'Max','瑟斐斯':'Zephys','呂布':'Lu Bu','趙雲':'Zanis','馬洛斯':'Maloch','莫托斯':'Arthur','愛里':'Airi','司科德':'Skud','祖卡':'Zuka','超人':'Superman','凱格路士':'Kil’Groth','龍馬':'Ryoma','艾翠絲':'Astrid','神力女超人':'Wonder Woman','夜叉':'Omen','洛克':'Rourke','艾蜜莉':'Amily','瑞克':'Riktor','緋淚':'Veres','弗洛倫':'Florentino','埃羅':'Errol','葉娜':'Yena','筱清':'Qi','安格列':'Volkath','亞連':'Allain','青硯':'Tachi','霧己':'Yan','夜姬':'Dextra',
'刀鋒寶貝':'Butterfly','納克羅斯':'Nakroth','悟空':'Wukong','科里納卡':'Kriknak','蝙蝠俠':'Batman','莫拉':'Murad','奎倫':'Quillen','銀晝':'Enzo','綺蘿':'Keera','潘因':'Paine','颯枷':'Zata','蘇離':'Sinestrea','星葵':'Aoi','布萊特':'Bright','齊爾':'Zill','閃電俠':'The Flash','拉茲':'Raz',
'薇菈':'Veera','阿茲卡':'Azzen’Ka','盧蜜亞':'Ilumia','蘿兒':'Lauriel','貂蟬':'Diaochan','阿萊斯特':'Aleister','克里希':'Krixi','卡莉':'Kahlii','穆加爵':'Mganga','普雷塔':'Preyta','娜塔亞':'Natalya','金納':'Jinnar','伊耿士':'Ignis','圖倫':'Tulen','莉莉安':'Liliana','瑪迦':'Marja','瀾':'Sephera','達爾西':"D'Arcy",'依夏':'Ishar','狄拉克':'Dirak','伊格':'Iggy','洛里昂':'Lorion','令月':'Yue',
'堇':'Violet','勇':'Yorn','凡恩':'Valhein','菲尼克':'Fennik','史蘭茲':'Slimz','特爾安娜絲':"Tel'Annas",'小丑':'The Joker','摩恩':'Moren','琳蒂':'Lindis','靈靈':'Wisp','蘇':'Elsu','亥犽':'Hayate','卡芬妮':'Capheny','希露卡':'Celica','蘭鐸':"Eland'orr",'拉維爾':'Laville','索文':'Thorne','緹莉':'Teeri',
'愛麗絲':'Alice','克萊斯':'Cresht','夸克':'Grakk','朗博':'Lumburr','海倫':'Helen','提米':'TeeMee','安奈特':'Annette','皮皮':'Zip','卡瑞茲':'Krizzix','若伊':'Rouie','芽芽':'Aya'
};
// Pin to an actual upstream commit, not the heroes.json blob SHA.
const DATA_URL='https://raw.githubusercontent.com/MLuc24/lien-quan-data/af781f4d2b7417755c03968e7ee6410baf47b9ca/data/heroes.json';
const HP_OVERRIDE={'哥德爾':3378,'塔拉':3620,'阿塔':3720,'凡恩':3592,'伯頓':3483,'克萊斯':3450,'令月':3475};
const FALLBACK_HP={'美娜':3510,'薩尼':3535,'麥克思':3483,'瑟斐斯':3617,'呂布':3431,'趙雲':3434,'瑞克':3465,'弗洛倫':3535,'埃羅':3575,'悟空':3305,'蝙蝠俠':3292,'奎倫':3269,'綺蘿':3660,'閃電俠':3570,'薇菈':3579,'貂蟬':3358,'娜塔亞':3323,'金納':3472,'圖倫':3485,'瀾':2966,'伊格':3475,'史蘭茲':3292,'小丑':3377,'靈靈':3235,'朗博':3537,'提米':3201};
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’' ._-]/g,'')}
function score(items){const vals=items.map(x=>x.hp).sort((a,b)=>a-b);return items.map(x=>({...x,points:Math.max(1,Math.min(10,Math.floor(d3.bisectLeft(vals,x.hp)*10/vals.length)+1))}))}
async function loadSnapshot(){const r=await fetch(DATA_URL,{cache:'force-cache'});if(!r.ok)throw Error('無法載入固定血量資料');const raw=await r.json(),by=new Map();for(const h of raw){const hp=Number((h.stats||[]).find(s=>s.id==='maxhp')?.value);if(!Number.isFinite(hp))continue;[h.name,h.slug].filter(Boolean).forEach(k=>by.set(norm(k),hp))}const all=AOV_HEROES.map(h=>({name:h.name,role:h.role,hp:HP_OVERRIDE[h.name]??by.get(norm(EN[h.name]))??by.get(norm(h.name))??FALLBACK_HP[h.name]}));if(all.length!==115)throw Error('英雄名單數量異常：'+all.length+' 位');const missing=all.filter(x=>!Number.isFinite(x.hp)).map(x=>x.name);if(missing.length)throw Error('血量資料仍缺少：'+missing.join('、'));return{items:score(all),skipped:[]}}
function addButton(){const card=[...document.querySelectorAll('#home .card')].find(c=>c.querySelector('h2')?.textContent.includes('傳說對決英雄'));if(!card||card.querySelector('.aovHpBtn'))return;let wrap=card.querySelector('.modeBtns');if(!wrap){wrap=document.createElement('div');wrap.className='modeBtns';card.appendChild(wrap);const solo=document.createElement('button');solo.className='singleBtn';solo.textContent='單人';solo.onclick=e=>{e.preventDefault();e.stopPropagation();window.TinaRouter?.go('aov')||(location.hash='aov')};wrap.appendChild(solo)}wrap.style.gridTemplateColumns='1fr 1fr';const b=document.createElement('button');b.className='territoryBtn aovHpBtn';b.textContent='❤️ 血量 PK';b.onclick=e=>{e.preventDefault();e.stopPropagation();window.TinaRouter?.go('aov-hp-pk')||(location.hash='aov-hp-pk')};wrap.appendChild(b)}
async function startAovHpPK(){document.getElementById('aovHpBoard')?.remove();map.style.display='none';title.textContent='❤️ 傳說英雄血量 PK';ans.placeholder='輸入英雄名稱';document.querySelector('.score').style.display='none';const board=document.createElement('div');board.id='aovHpBoard';board.className='pkBoard';map.parentElement.appendChild(board);board.innerHTML='<div style="text-align:center;padding:40px 10px;color:#68717a">檢查英雄血量資料…</div>';let loaded;try{loaded=await loadSnapshot()}catch(e){board.innerHTML='<div class="bad" style="padding:20px;line-height:1.6"><b>血量資料載入失敗，遊戲未開始。</b><br>'+String(e.message||e)+'</div>';go.disabled=finish.disabled=true;return}const items=loaded.items,skipped=loaded.skipped,lookup=new Map(items.map(x=>[N(x.name),x])),used=new Set(),scores=[0,0],history=[];let turn=0,passes=0,done=false,submitting=false;
board.innerHTML='<div class="pkPlayers"><div class="pkPlayer" id="aovP0"><b>玩家 1</b><div class="pkScore" id="aovS0">0 分</div></div><div class="pkVs">VS</div><div class="pkPlayer" id="aovP1"><b>玩家 2</b><div class="pkScore" id="aovS1">0 分</div></div></div><div class="pkRule">兩人輪流輸入英雄。Lv.1 裸裝基礎生命值越高，固定得分越高（1～10 分）；同一英雄只能佔領一次。連續兩次 Pass 或按「公布答案」即結束。</div><button class="territoryPass" id="aovHpPass">Pass</button><div class="territoryLegend"><span id="aovL0">玩家 1：0 分</span><span id="aovL1">玩家 2：0 分</span></div><div class="pkHistory" id="aovHist"></div>';
const p=[board.querySelector('#aovP0'),board.querySelector('#aovP1')],s=[board.querySelector('#aovS0'),board.querySelector('#aovS1')],l=[board.querySelector('#aovL0'),board.querySelector('#aovL1')],hist=board.querySelector('#aovHist'),passBtn=board.querySelector('#aovHpPass');
function render(){for(let i=0;i<2;i++){p[i].classList.toggle('active',turn===i&&!done);s[i].textContent=scores[i]+' 分';l[i].textContent='玩家 '+(i+1)+'：'+scores[i]+' 分'}passBtn.disabled=done;hist.innerHTML=history.slice().reverse().map(h=>`<div class="pkLog ${h.ok?'ok':'bad'}">${h.text}</div>`).join('')}
function say(t,ok){msg.innerHTML=`<span class="${ok?'ok':'bad'}">${t}</span>`}
function clearFocus(){ans.value='';requestAnimationFrame(()=>ans.focus())}
function submit(){if(done||submitting)return;const raw=ans.value.trim();if(!raw)return;submitting=true;const x=lookup.get(N(raw));if(!x){say('✕ 目前沒有這位英雄的可靠血量資料。',false);submitting=false;clearFocus();return}if(used.has(x.name)){say('✕ '+x.name+' 已經被佔領。',false);submitting=false;clearFocus();return}const player=turn;used.add(x.name);scores[player]+=x.points;history.push({ok:true,text:`玩家 ${player+1}｜${x.name}｜${x.hp} HP｜+${x.points} 分`});passes=0;turn=1-turn;render();say(`✓ ${x.name}：${x.hp} HP，玩家 ${player+1} +${x.points} 分；輪到玩家 ${turn+1}`,true);submitting=false;clearFocus()}
function pass(){if(done||submitting)return;const player=turn;history.push({ok:false,text:`玩家 ${player+1} Pass`});passes++;turn=1-turn;if(passes>=2)return end(false);render();say(`玩家 ${player+1} Pass；輪到玩家 ${turn+1}`,true);ans.focus()}
function end(reveal=true){if(done)return;done=true;go.disabled=finish.disabled=true;const winner=scores[0]===scores[1]?'平手':scores[0]>scores[1]?'玩家 1 勝利':'玩家 2 勝利';missing.style.display='block';const left=items.filter(x=>!used.has(x.name)).sort((a,b)=>b.hp-a.hp);missing.innerHTML=`<b>${winner}｜${scores[0]} : ${scores[1]}</b><br>已佔領 ${used.size}/${items.length}`+(reveal?`<br><br><b>未佔領英雄（血量／分數）</b><br>${left.map(x=>`${x.name} ${x.hp} HP（${x.points}分）`).join('、')}`:'')+(skipped.length?`<br><br><small>未納入：${skipped.length} 位缺可靠血量資料的英雄。</small>`:'');render();window.TinaGuard?.markFinished?.()}
go.disabled=finish.disabled=false;go.onclick=submit;finish.textContent='公布答案';finish.onclick=()=>end(true);passBtn.onclick=pass;ans.onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();submit()}};render();say(`玩家 1 先開始（${items.length} 位英雄全部納入）`,true);ans.focus()}
window.startAovHpPK=startAovHpPK;window.addEventListener('DOMContentLoaded',addButton);if(document.readyState!=='loading')addButton();
})();