(()=>{
let bypass=false,extendedPkLoaded=false;
const gameVisible=()=>{const g=document.getElementById('game');return !!g&&getComputedStyle(g).display!=='none'};
const TG=()=>window.TinaGuard;
// Finish/reveal guard only. Navigation/back handling lives in nav-guard.js, which is
// deliberately loaded before every router so Safari Back cannot race game cleanup.
document.addEventListener('click',e=>{if(bypass)return;const btn=e.target.closest('#finish');if(!btn||btn.disabled||!gameVisible())return;const text=(btn.textContent||'').trim();if(!/(交卷|公布答案|結束)/.test(text))return;e.preventDefault();e.stopImmediatePropagation();if(TG()&&!TG().confirmReveal())return;bypass=true;try{btn.click();TG()?.markFinished()}finally{bypass=false}},true);
const guardObserver=new MutationObserver(()=>{const f=document.getElementById('finish'),g=document.getElementById('go');if(gameVisible()&&f&&g&&f.disabled&&g.disabled)TG()?.markFinished()});guardObserver.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['style','disabled']});
const musicExtra=document.createElement('script');musicExtra.src='music-extra.js?v=20260915-12';musicExtra.onload=()=>{const lyrics=document.createElement('script');lyrics.src='lyrics-game.js?v=20260915-12';lyrics.onload=()=>{const extra=document.createElement('script');extra.src='lyrics-extra.js?v=20260915-12';extra.onload=()=>{const ui=document.createElement('script');ui.src='lyrics-ui.js?v=20260915-12';ui.onload=()=>setTimeout(verifyRoute,0);document.head.appendChild(ui)};document.head.appendChild(extra)};document.head.appendChild(lyrics)};document.head.appendChild(musicExtra);
const priceExtra=document.createElement('script');priceExtra.src='pricing-extra.js?v=20260915-12';document.head.appendChild(priceExtra);
const musicIds=['831','bestards','cosmos','samlee','fahrenheit','sasha'];
function restoreBaseUI(){const controls=document.querySelector('.controls'),score=document.querySelector('.score'),map=document.getElementById('map');if(controls)controls.style.display='block';if(score)score.style.display='block';if(map)map.style.display='block'}
function fixBaseMusicRoute(){const q=(location.hash||'').slice(1);if(!musicIds.includes(q)||typeof MUSIC_GAMES==='undefined'||!MUSIC_GAMES[q])return;const needs=!gameVisible()||document.querySelector('.controls')?.style.display==='none'||!document.getElementById('musicBoard');if(!needs)return;currentGame=q;resetUI();restoreBaseUI();home.style.display='none';game.style.display='flex';musicGame(q);TG()?.markActive()}
function loadExtendedPK(){if(extendedPkLoaded)return;extendedPkLoaded=true;const s=document.createElement('script');s.src='pk.js?v=20260915-music12';s.onload=()=>setTimeout(verifyRoute,0);document.head.appendChild(s)}
function verifyRoute(){const q=(location.hash||'').slice(1);if(!q)return;if(musicIds.includes(q)){fixBaseMusicRoute();return}const lm=q.match(/^(831|bestards|cosmos|samlee|fahrenheit|sasha)-lyrics-(guess|fill)(-pk)?$/);if(lm&&typeof startLyricGame==='function'&&!document.getElementById('lyricBoard')){currentGame=q;startLyricGame(lm[1],lm[2],!!lm[3]);TG()?.markActive();return}if((q==='pk-fahrenheit'||q==='pk-sasha')&&!document.querySelector('.pkBoard')&&typeof MUSIC_GAMES!=='undefined'&&MUSIC_GAMES[q.slice(3)]){loadExtendedPK();return}if((q==='price'||q==='pk-price')&&!document.getElementById('priceBoard')){const fn=q==='price'?window.startPriceSolo:window.startPricePK;if(typeof fn==='function'){currentGame=q;fn();TG()?.markActive();return}}if((q==='timeline'||q==='pk-timeline')&&!document.getElementById('timelineBoard')){const fn=q==='timeline'?window.startTimelineSolo:window.startTimelinePK;if(typeof fn==='function'){currentGame=q;fn();TG()?.markActive();return}}}
window.addEventListener('hashchange',()=>setTimeout(verifyRoute,60));musicExtra.addEventListener('load',()=>setTimeout(verifyRoute,60));setTimeout(verifyRoute,250);
function fixPriceUI(){const card=[...document.querySelectorAll('#home .card')].find(c=>c.querySelector('h2')?.textContent.trim()==='價格猜猜看');if(card){const groups=[...card.querySelectorAll('.modeBtns')];groups.slice(1).forEach(g=>g.remove())}const board=document.getElementById('priceBoard');if(board){const old=[...board.querySelectorAll('div')].find(d=>d.children.length===0&&d.textContent.includes('越接近標準答案分數越高'));if(old&&!old.dataset.fullPriceRule){old.dataset.fullPriceRule='1';old.innerHTML='<b style="color:#68717a">計分方式｜與標準價格的誤差</b><br>≤ 5%：100 分　｜　≤ 10%：80 分<br>≤ 20%：60 分　｜　≤ 30%：40 分<br>≤ 50%：20 分　｜　&gt; 50%：0 分';old.style.lineHeight='1.75';old.style.fontSize='12px';old.style.color='#8a9198';old.style.textAlign='center'}}}
window.addEventListener('DOMContentLoaded',fixPriceUI);new MutationObserver(fixPriceUI).observe(document.documentElement,{childList:true,subtree:true});
})();