(()=>{
let bypass=false,active=false,finished=false,trap=false,finishedHash='',activeUrl='';
function gameVisible(){const g=document.getElementById('game');return !!g&&getComputedStyle(g).display!=='none'}
function confirmReveal(message){return window.confirm(message||'確定要公布答案嗎？\n公布後這局就會結束，無法繼續作答。')}
function confirmLeave(){return window.confirm('確定要離開這局嗎？\n目前的作答進度與已公布答案會消失。')}
function markActive(){if(active&&!finished&&activeUrl===location.href)return;active=true;finished=false;finishedHash='';activeUrl=location.href;if(!trap){history.pushState({tinaGuard:true},'',activeUrl);trap=true}}
function markFinished(){finished=true;active=false;trap=false;finishedHash=location.hash;activeUrl=''}
window.TinaGuard={confirmReveal,confirmLeave,markActive,markFinished};
function autoGuard(){if(gameVisible()&&location.hash&&location.hash!==finishedHash&&!active&&!finished)markActive()}
// One same-URL guard entry sits in front of an active game. Browser Back lands on
// the real game entry first, so we can ask before allowing the second Back to leave.
window.addEventListener('popstate',()=>{if(bypass||!active||finished||!trap)return;trap=false;if(confirmLeave()){active=false;activeUrl='';bypass=true;history.back();setTimeout(()=>bypass=false,180)}else{bypass=true;history.forward();setTimeout(()=>{bypass=false;trap=true},180)}});
document.addEventListener('click',e=>{if(bypass)return;const btn=e.target.closest('#finish');if(!btn||btn.disabled||!gameVisible())return;const text=(btn.textContent||'').trim();if(!/(交卷|公布答案|結束)/.test(text))return;e.preventDefault();e.stopImmediatePropagation();if(!confirmReveal())return;bypass=true;try{btn.click();markFinished()}finally{bypass=false}},true);
document.addEventListener('click',e=>{if(bypass||!active||finished||!gameVisible())return;const back=e.target.closest('.back');if(!back)return;e.preventDefault();e.stopImmediatePropagation();if(!confirmLeave())return;active=false;trap=false;activeUrl='';bypass=true;location.hash='';setTimeout(()=>bypass=false,0)},true);
window.addEventListener('beforeunload',e=>{if(!active||finished||bypass)return;e.preventDefault();e.returnValue=''});
window.addEventListener('hashchange',()=>setTimeout(autoGuard,0));
const guardObserver=new MutationObserver(()=>{autoGuard();const f=document.getElementById('finish'),g=document.getElementById('go');if(active&&gameVisible()&&f&&g&&f.disabled&&g.disabled)markFinished()});guardObserver.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['style','disabled']});
setTimeout(autoGuard,0);
const musicExtra=document.createElement('script');musicExtra.src='music-extra.js?v=20260915-9';musicExtra.onload=()=>{const lyrics=document.createElement('script');lyrics.src='lyrics-game.js?v=20260915-9';lyrics.onload=()=>{const extra=document.createElement('script');extra.src='lyrics-extra.js?v=20260915-9';extra.onload=()=>{const ui=document.createElement('script');ui.src='lyrics-ui.js?v=20260915-9';ui.onload=()=>setTimeout(verifyRoute,0);document.head.appendChild(ui)};document.head.appendChild(extra)};document.head.appendChild(lyrics)};document.head.appendChild(musicExtra);
const priceExtra=document.createElement('script');priceExtra.src='pricing-extra.js?v=20260915-9';document.head.appendChild(priceExtra);
const musicIds=['831','bestards','cosmos','samlee','fahrenheit','sasha'];
function restoreBaseUI(){const controls=document.querySelector('.controls'),score=document.querySelector('.score'),map=document.getElementById('map');if(controls)controls.style.display='block';if(score)score.style.display='block';if(map)map.style.display='block'}
function fixBaseMusicRoute(){const q=(location.hash||'').slice(1);if(!musicIds.includes(q)||typeof MUSIC_GAMES==='undefined'||!MUSIC_GAMES[q])return;const needs=!gameVisible()||document.querySelector('.controls')?.style.display==='none'||!document.getElementById('musicBoard');if(!needs)return;currentGame=q;resetUI();restoreBaseUI();home.style.display='none';game.style.display='flex';musicGame(q);markActive()}
function verifyRoute(){const q=(location.hash||'').slice(1);if(!q)return;if(musicIds.includes(q)){fixBaseMusicRoute();return}const lm=q.match(/^(831|bestards|cosmos|samlee|fahrenheit|sasha)-lyrics-(guess|fill)(-pk)?$/);if(lm&&typeof startLyricGame==='function'&&!document.getElementById('lyricBoard')){currentGame=q;startLyricGame(lm[1],lm[2],!!lm[3]);return}if((q==='price'||q==='pk-price')&&!document.getElementById('priceBoard')){const fn=q==='price'?window.startPriceSolo:window.startPricePK;if(typeof fn==='function'){currentGame=q;fn();return}}if((q==='timeline'||q==='pk-timeline')&&!document.getElementById('timelineBoard')){const fn=q==='timeline'?window.startTimelineSolo:window.startTimelinePK;if(typeof fn==='function'){currentGame=q;fn();return}}}
window.addEventListener('hashchange',()=>setTimeout(verifyRoute,60));musicExtra.addEventListener('load',()=>setTimeout(verifyRoute,60));setTimeout(verifyRoute,250);
function fixPriceUI(){const card=[...document.querySelectorAll('#home .card')].find(c=>c.querySelector('h2')?.textContent.trim()==='價格猜猜看');if(card){const groups=[...card.querySelectorAll('.modeBtns')];groups.slice(1).forEach(g=>g.remove())}const board=document.getElementById('priceBoard');if(board){const old=[...board.querySelectorAll('div')].find(d=>d.children.length===0&&d.textContent.includes('越接近標準答案分數越高'));if(old&&!old.dataset.fullPriceRule){old.dataset.fullPriceRule='1';old.innerHTML='<b style="color:#68717a">計分方式｜與標準價格的誤差</b><br>≤ 5%：100 分　｜　≤ 10%：80 分<br>≤ 20%：60 分　｜　≤ 30%：40 分<br>≤ 50%：20 分　｜　&gt; 50%：0 分';old.style.lineHeight='1.75';old.style.fontSize='12px';old.style.color='#8a9198';old.style.textAlign='center'}}}
window.addEventListener('DOMContentLoaded',fixPriceUI);new MutationObserver(fixPriceUI).observe(document.documentElement,{childList:true,subtree:true});
})();