(()=>{function install(){if(typeof LYRIC_BANK==='undefined'||typeof startLyricGame==='undefined'){setTimeout(install,0);return}if(window.__lyricsExtraInstalled)return;window.__lyricsExtraInstalled=true;
LYRIC_BANK.fahrenheit=[
['我有我的Young',['我有我的 young','夢想每一刻都在發光']],['夏雪',['你給的愛帶著夏天的雪','融化了心的某一邊']],['只對你有感覺',['只對你有感覺','微笑再美再甜不是你的都不特別']],['愛到',['愛到愛到愛到腦海裡全是你','愛到最後只能更愛你']],['出神入化',['這是我的時代由我給你未來','出神入化是非都被我融化']],['不會愛',['我不會愛但為你我會學','沒有你愛不會存在']],['Ti Amo',['Ti Amo Ti Amo','愛你的心無法忘掉']],['越來越愛',['越來越愛大聲表白','愛就要讓你知道']],['寂寞暴走',['我的寂寞在暴走','思念像怪獸吞沒我']],['默默',['我可以永遠笑著扮演你的配角','在你的背後自己煎熬']],['留下來',['留下來留下來','可不可以不要走']],['孤單摩天輪',['旋轉木馬停止轉動','孤單摩天輪還在等候']],['太熱',['太熱太熱愛太熱','心跳快要失控']],['心疼妳的心疼',['我心疼你的心疼','想把你的痛都帶走']],['很安靜',['我的世界突然變得很安靜','聽見自己想你的聲音']]
];
LYRIC_BANK.sasha=[
['Older',["I used to shut my door","The older I get"]],['Dancing With Your Ghost',["I stay up all night","Dancing with your ghost"]],['Too Sad to Cry',["I'm too sad to cry","Nothing can make me feel"]],['Keep On',["I know it gets better","I just gotta keep on"]],['Only Child',["I wish I had a sister","I'm an only child"]],['House With No Mirrors',["I'd be happier without my fears","A house with no mirrors"]],['Lie',["Don't tell me the truth","Tell me that you love me"]],['I Blame The World',["I blame the world","Nothing really matters"]],['WTF',["What the fuck am I doing","I don't know why I'm here"]],['Me Again',["I can't wait to want","I wanna be me again"]],['Cowboys Cry',["Even cowboys cry","You don't have to hide"]],['Kids',["We were just kids","Time goes way too fast"]],['Highlights',["You only see the highlights","You don't know the whole story"]],['Good Enough',["I never feel good enough","Maybe I was always enough"]],['Picked First',["Took the first flight I could get home","Walked up to your floor"]]
];
// Prefer five different songs, but if an older bank has fewer than five songs,
// fill the round with a different lyric line instead of refusing to start.
lyricPick5=function(artist){const pool=lyricShuffle(lyricPool(artist)),usedSongs=new Set(),usedKeys=new Set(),out=[];for(const x of pool){if(usedSongs.has(x.song))continue;usedSongs.add(x.song);usedKeys.add(x.key);out.push(x);if(out.length===5)return out}for(const x of pool){if(usedKeys.has(x.key))continue;usedKeys.add(x.key);out.push(x);if(out.length===5)break}return out};
// English fill: blank 2–6 whole words. Chinese fill keeps blanking 2–6 Han characters. Punctuation is never part of the answer.
makeFill=function(q){const line=q.line;if(/[A-Za-z]/.test(line)&&!/[\u3400-\u9fff]/.test(line)){const words=line.trim().split(/\s+/);if(words.length<3)return null;const max=Math.min(6,Math.max(2,words.length-1)),len=Math.min(max,Math.max(2,Math.floor(Math.random()*(max-1))+2)),start=Math.floor(Math.random()*(words.length-len+1));return{prompt:[...words.slice(0,start),'＿'.repeat(len),...words.slice(start+len)].join(' '),answer:words.slice(start,start+len).join(' ')}}const chars=[...line],runs=[];let s=null;for(let i=0;i<=chars.length;i++){const ok=i<chars.length&&/[\u3400-\u9fff]/.test(chars[i]);if(ok&&s===null)s=i;if(!ok&&s!==null){if(i-s>=4)runs.push([s,i]);s=null}}if(!runs.length){const han=chars.map((c,i)=>/[\u3400-\u9fff]/.test(c)?i:-1).filter(i=>i>=0);if(han.length<2)return null;const len=Math.min(2,han.length),start=han[0];return{prompt:chars.map((c,i)=>i>=start&&i<start+len&&/[\u3400-\u9fff]/.test(c)?'＿':c).join(''),answer:chars.slice(start,start+len).join('')}}const [a,z]=runs[Math.floor(Math.random()*runs.length)],max=Math.min(6,z-a),len=Math.max(2,Math.floor(Math.random()*(max-1))+2),start=a+Math.floor(Math.random()*(z-a-len+1));return{prompt:chars.slice(0,start).join('')+'＿'.repeat(len)+chars.slice(start+len).join(''),answer:chars.slice(start,start+len).join('')}};
function route(){const h=(location.hash||'').slice(1),m=h.match(/^(fahrenheit|sasha)-lyrics-(guess|fill)(-pk)?$/);if(!m)return;currentGame=h;startLyricGame(m[1],m[2],!!m[3])}window.addEventListener('hashchange',route);route();
}install()})();