(()=>{function install(){if(typeof LYRIC_BANK==='undefined'||typeof startLyricGame==='undefined'){setTimeout(install,0);return}if(window.__lyricsExtraInstalled)return;window.__lyricsExtraInstalled=true;
LYRIC_BANK.fahrenheit=[
['我有我的Young',['我有我的 young','夢想每一刻都在發光']],['夏雪',['你給的愛帶著夏天的雪','融化了心的某一邊']],['只對你有感覺',['只對你有感覺','微笑再美再甜不是你的都不特別']],['愛到',['愛到愛到愛到腦海裡全是你','愛到最後只能更愛你']],['出神入化',['這是我的時代由我給你未來','出神入化是非都被我融化']],['不會愛',['我不會愛但為你我會學','沒有你愛不會存在']],['Ti Amo',['Ti Amo Ti Amo','愛你的心無法忘掉']],['越來越愛',['越來越愛大聲表白','愛就要讓你知道']],['寂寞暴走',['我的寂寞在暴走','思念像怪獸吞沒我']],['默默',['我可以永遠笑著扮演你的配角','在你的背後自己煎熬']],['留下來',['留下來留下來','可不可以不要走']],['孤單摩天輪',['旋轉木馬停止轉動','孤單摩天輪還在等候']],['太熱',['太熱太熱愛太熱','心跳快要失控']],['心疼妳的心疼',['我心疼你的心疼','想把你的痛都帶走']],['很安靜',['我的世界突然變得很安靜','聽見自己想你的聲音']]
];
LYRIC_BANK.sasha=[
['Older',["I used to shut my door","The older I get"]],['Dancing With Your Ghost',["I stay up all night","Dancing with your ghost"]],['Too Sad to Cry',["I'm too sad to cry","Nothing can make me feel"]],['Keep On',["I know it gets better","I just gotta keep on"]],['Only Child',["I wish I had a sister","I'm an only child"]],['House With No Mirrors',["I'd be happier without my fears","A house with no mirrors"]],['Lie',["Don't tell me the truth","Tell me that you love me"]],['I Blame The World',["I blame the world","Nothing really matters"]],['WTF',["What the fuck am I doing","I don't know why I'm here"]],['Me Again',["I can't wait to want","I wanna be me again"]],['Cowboys Cry',["Even cowboys cry","You don't have to hide"]],['Kids',["We were just kids","Time goes way too fast"]],['Highlights',["You only see the highlights","You don't know the whole story"]],['Good Enough',["I never feel good enough","Maybe I was always enough"]],['Picked First',["Took the first flight I could get home","Walked up to your floor"]]
];
function recentKey(artist){return'tinaLyricRecent:'+artist}function readRecent(artist){try{const x=JSON.parse(localStorage.getItem(recentKey(artist))||'[]');return Array.isArray(x)?x.slice(-20):[]}catch(e){return[]}}function saveRecent(artist,keys){try{localStorage.setItem(recentKey(artist),JSON.stringify([...readRecent(artist),...keys].slice(-20)))}catch(e){}}
lyricPick5=function(artist){const pool=lyricShuffle(lyricPool(artist)),recent=new Set(readRecent(artist)),usedSongs=new Set(),usedKeys=new Set(),out=[];function take(filter,sameSongOK){for(const x of pool){if(out.length===5)break;if(usedKeys.has(x.key)||!filter(x)||(!sameSongOK&&usedSongs.has(x.song)))continue;usedSongs.add(x.song);usedKeys.add(x.key);out.push(x)}}take(x=>!recent.has(x.key),false);take(x=>recent.has(x.key),false);take(x=>!recent.has(x.key),true);take(()=>true,true);saveRecent(artist,out.map(x=>x.key));return out};
// Keep enough context on both sides of a blank. Avoid clues such as 我＿＿＿＿ where only one visible character remains.
makeFill=function(q){const line=q.line;if(/[A-Za-z]/.test(line)&&!/[\u3400-\u9fff]/.test(line)){const words=line.trim().split(/\s+/);if(words.length<4)return null;const candidates=[];for(let len=2;len<=Math.min(4,words.length-2);len++)for(let start=1;start+len<words.length;start++)candidates.push([start,len]);if(!candidates.length)return null;const [start,len]=candidates[Math.floor(Math.random()*candidates.length)];return{prompt:[...words.slice(0,start),'＿'.repeat(len),...words.slice(start+len)].join(' '),answer:words.slice(start,start+len).join(' ')}}const chars=[...line],hanIdx=chars.map((c,i)=>/[\u3400-\u9fff]/.test(c)?i:-1).filter(i=>i>=0);if(hanIdx.length<5)return null;const candidates=[];for(let len=2;len<=Math.min(4,hanIdx.length-3);len++){for(let p=1;p+len<hanIdx.length-1;p++){const start=hanIdx[p],end=hanIdx[p+len-1];if(end-start===len-1)candidates.push([start,len])}}if(!candidates.length)return null;const [start,len]=candidates[Math.floor(Math.random()*candidates.length)];return{prompt:chars.slice(0,start).join('')+'＿'.repeat(len)+chars.slice(start+len).join(''),answer:chars.slice(start,start+len).join('')}};
// Patch result rendering so fill-in answers always reveal the source song as well.
const baseStart=startLyricGame;startLyricGame=function(artist,type,pk){baseStart(artist,type,pk);if(type!=='fill')return;const board=document.getElementById('lyricBoard');if(!board)return;const observer=new MutationObserver(()=>{if(!board.isConnected){observer.disconnect();return}const label=[...board.querySelectorAll('div')].find(x=>x.children.length===0&&x.textContent.trim()==='正確答案');if(!label)return;const source=[...board.querySelectorAll('div')].find(x=>x.children.length===0&&x.textContent.trim().startsWith('出處：'));if(source){source.textContent=source.textContent.replace(/^出處：/,'歌名：');source.style.fontSize='15px';source.style.fontWeight='700';source.style.color='#68717a'}});observer.observe(board,{childList:true,subtree:true})};
function route(){const h=(location.hash||'').slice(1),m=h.match(/^(fahrenheit|sasha)-lyrics-(guess|fill)(-pk)?$/);if(!m)return;currentGame=h;startLyricGame(m[1],m[2],!!m[3])}window.addEventListener('hashchange',route);route();
}install()})();