(()=>{
const BANKS={};
function add(key,title,items,aliases={}){const lookup=new Map();for(const item of items){lookup.set(N(item.name),item.name);for(const a of (aliases[item.name]||[]))lookup.set(N(a),item.name)}BANKS[key]={title,items:items.map(x=>x.name),lookup}}
function initBanks(){
add('aov','⚔️ 傳說對決英雄 PK',AOV_HEROES);
if(typeof MUSIC_GAMES!=='undefined')for(const [k,g] of Object.entries(MUSIC_GAMES))add(k,g.title.replace('大挑戰','PK'),g.songs,g.aliases||{});
add('countries','🌍 世界國家 PK',DATA.map(x=>({name:x.zh})),Object.fromEntries(DATA.map(x=>[x.zh,[x.en,x.code]])));
add('capitals','🌎 世界首都 PK',DATA.map(x=>({name:CAP_TW[x.capital]||x.capital})),Object.fromEntries(DATA.map(x=>[CAP_TW[x.capital]||x.capital,[x.capital,...(CAP_ALIAS[x.capital]||[])]])));
add('japan','🗾 日本行政區 PK',JP.map(x=>({name:x.zh})),Object.fromEntries(JP.map(x=>[x.zh,[x.jp,x.en,x.zh.replace(/縣$/,''),x.zh.replace(/[府都]$/,'')]])));
add('us','🇺🇸 美國州 PK',US.map(x=>({name:x.zh})),Object.fromEntries(US.map(x=>[x.zh,[x.en,x.abbr,x.zh.replace(/州$/,'')]])));
}
function homeButtons(){document.querySelectorAll('#home .card').forEach(card=>{const key=(card.getAttribute('href')||'').slice(1);if(!key||card.querySelector('.pkBtn'))return;const b=document.createElement('button');b.className='pkBtn';b.textContent='⚔️ 雙人 PK';b.onclick=e=>{e.preventDefault();e.stopPropagation();location.hash='pk-'+key};card.appendChild(b)})}
function startPK(key){const bank=BANKS[key];if(!bank)return false;home.style.display='none';game.style.display='flex';map.style.display='none';document.querySelector('#heroBoard')?.remove();document.querySelector('#musicBoard')?.remove();title.textContent=bank.title;total.textContent='3命';n.textContent='';ans.placeholder='輪流輸入答案';go.disabled=false;finish.disabled=false;finish.textContent='結束';msg.style.display='block';missing.style.display='block';missing.innerHTML='';
const box=document.createElement('div');box.className='pkBoard';map.parentElement.appendChild(box);let turn=0,lives=[3,3],scores=[0,0],used=new Set(),ended=false;const names=['玩家 1','玩家 2'];
box.innerHTML=`<div class="pkPlayers"><div class="pkPlayer active" id="p0"><b>${names[0]}</b><span class="pkScore">0 題</span><span class="pkLives">❤️❤️❤️</span></div><div class="pkVs">VS</div><div class="pkPlayer" id="p1"><b>${names[1]}</b><span class="pkScore">0 題</span><span class="pkLives">❤️❤️❤️</span></div></div><div class="pkRule">輪流回答，每次只能答一個。答錯、重複或想不出來可按「跳過」，會失去 1 條命；先歸零的人輸。</div><button id="passBtn" class="pkPass">跳過／想不出來 −1 ❤️</button><div id="pkHistory" class="pkHistory"></div>`;
const ps=[box.querySelector('#p0'),box.querySelector('#p1')],history=box.querySelector('#pkHistory');function render(){for(let i=0;i<2;i++){ps[i].classList.toggle('active',i===turn&&!ended);ps[i].querySelector('.pkScore').textContent=scores[i]+' 題';ps[i].querySelector('.pkLives').textContent='❤️'.repeat(lives[i])+'🖤'.repeat(3-lives[i])}msg.innerHTML=ended?'':`<span class="ok">輪到 ${names[turn]}</span>`}function log(t,ok){const d=document.createElement('div');d.className=ok?'pkLog ok':'pkLog bad';d.textContent=t;history.prepend(d)}function next(){turn=1-turn;render();ans.value='';ans.focus()}function lose(reason){lives[turn]--;log(`${names[turn]}：${reason} −1 ❤️`,false);if(lives[turn]<=0){ended=true;go.disabled=true;box.querySelector('#passBtn').disabled=true;msg.innerHTML=`<b>🏆 ${names[1-turn]} 獲勝！</b>　${scores[0]}：${scores[1]}`;return}next()}function submit(){if(ended)return;const raw=ans.value.trim();if(!raw)return;const hit=bank.lookup.get(N(raw));if(!hit){lose(`「${raw}」不在題庫`);return}if(used.has(hit)){lose(`「${hit}」已經答過`);return}used.add(hit);scores[turn]++;log(`${names[turn]} ✓ ${hit}`,true);next()}go.onclick=submit;box.querySelector('#passBtn').onclick=()=>lose('跳過');finish.onclick=()=>{ended=true;go.disabled=true;box.querySelector('#passBtn').disabled=true;const winner=scores[0]===scores[1]?'平手':names[scores[0]>scores[1]?0:1]+' 勝';msg.innerHTML=`<b>PK 結束：${winner}</b>　${scores[0]}：${scores[1]}`};ans.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();submit()}};render();ans.focus();return true}
initBanks();homeButtons();const original=window.onhashchange;window.addEventListener('hashchange',()=>{const q=(location.hash||'').slice(1);if(q.startsWith('pk-')){currentGame=q;resetUI();document.querySelector('.pkBoard')?.remove();startPK(q.slice(3))}else document.querySelector('.pkBoard')?.remove()});const first=(location.hash||'').slice(1);if(first.startsWith('pk-')){currentGame=first;resetUI();startPK(first.slice(3))}
})();