(()=>{
let ready=false,routing=false,last='',repairTimer=0,pendingBack=null;
const q=()=>decodeURIComponent((location.hash||'').replace(/^#/,''));
const genericPK=/^pk-(countries|capitals|japan|us|china|aov|831|bestards|cosmos|samlee|fahrenheit|sasha)$/;
const territory=/^territory-(countries|japan|us|taiwan|china)-(area|population|density|gdp|military)$/;
function owned(route){return !genericPK.test(route)&&!territory.test(route)}
function gameVisible(){const g=document.getElementById('game');return !!g&&getComputedStyle(g).display!=='none'}
function protectBack(){const top=document.querySelector('#game .top'),back=document.querySelector('#game .back');if(top){top.style.position='relative';top.style.zIndex='100';top.style.pointerEvents='auto'}if(back){back.style.position='relative';back.style.zIndex='101';back.style.pointerEvents='auto';back.style.touchAction='manipulation';back.style.minWidth='36px';back.style.minHeight='36px';back.style.display='flex';back.style.alignItems='center';back.style.justifyContent='center'}}
function homeView(){clearTimeout(repairTimer);if(typeof currentGame!=='undefined')currentGame=null;if(typeof resetUI==='function')resetUI();const h=document.getElementById('home'),g=document.getElementById('game');if(g)g.style.display='none';if(h){h.style.display='block';h.style.pointerEvents='auto'}document.body.style.pointerEvents='auto'}
function gameView(){const h=document.getElementById('home'),g=document.getElementById('game');if(h)h.style.display='none';if(g)g.style.display='flex';protectBack()}
function normalizeSpecialist(){const f=document.getElementById('finish');if(f)f.style.display='';protectBack()}
function titleFits(route){const t=(document.getElementById('title')?.textContent||'').trim();const names={countries:'世界國家',capitals:'世界首都',japan:'日本',us:'美國',taiwan:'台灣',china:'中國',aov:'傳說對決',831:'八三夭',bestards:'理想混蛋',cosmos:'宇宙人',samlee:'李聖傑',fahrenheit:'飛輪海',sasha:'Sasha Alex Sloan',price:'價格猜猜看',timeline:'時間線'};let base=route.replace(/^pk-/,'').replace(/^territory-/,'').split('-')[0].replace(/-lyrics-(guess|fill)(-pk)?$/,'');const needle=names[base];return !needle||t.includes(needle)}
function boardFits(route){if(!route)return !gameVisible();if(route==='price'||route==='pk-price')return !!document.getElementById('priceBoard');if(route==='timeline'||route==='pk-timeline')return !!document.getElementById('timelineBoard');if(/-lyrics-(guess|fill)/.test(route))return !!document.getElementById('lyricBoard');if(territory.test(route))return !!document.querySelector('.territoryBoard');if(genericPK.test(route)||route==='pk-taiwan')return !!document.querySelector('.pkBoard');return true}
function fireLegacy(){window.dispatchEvent(new HashChangeEvent('hashchange',{oldURL:location.href,newURL:location.href}))}
function repair(route){protectBack();if(q()!==route)return;if(!route){if(gameVisible())homeView();return}if(owned(route)){if(!gameVisible()||!titleFits(route)||!boardFits(route))run(route,true)}else if(!gameVisible()||!titleFits(route)||!boardFits(route)){normalizeSpecialist();fireLegacy()}}
function verify(route){clearTimeout(repairTimer);repairTimer=setTimeout(()=>repair(route),180)}
function run(route,force=false){if(!ready||routing)return false;route=route==null?q():route;if(!owned(route))return false;if(!force&&route===last&&route)return true;routing=true;try{if(!route){last='';homeView();return true}if(typeof currentGame!=='undefined')currentGame=route;if(typeof resetUI==='function')resetUI();gameView();let ok=true,m;if(['countries','capitals','japan','us','aov','831','bestards','cosmos','samlee','fahrenheit','sasha'].includes(route)){if(['fahrenheit','sasha'].includes(route)&&!(window.MUSIC_GAMES&&MUSIC_GAMES[route]))ok=false;else if(typeof start==='function')start(route);else ok=false}else if(route==='taiwan')ok=typeof startTaiwanSolo==='function'?(startTaiwanSolo(),true):false;else if(route==='china')ok=typeof startChina==='function'?(startChina(),true):false;else if(route==='price')ok=typeof startPriceSolo==='function'?(startPriceSolo(),true):false;else if(route==='pk-price')ok=typeof startPricePK==='function'?(startPricePK(),true):false;else if(route==='timeline')ok=typeof startTimelineSolo==='function'?(startTimelineSolo(),true):false;else if(route==='pk-timeline')ok=typeof startTimelinePK==='function'?(startTimelinePK(),true):false;else if(route==='pk-taiwan')ok=typeof startTaiwanPK==='function'?(startTaiwanPK(),true):false;else if((m=route.match(/^(831|bestards|cosmos|samlee|fahrenheit|sasha)-lyrics-(guess|fill)(-pk)?$/)))ok=typeof startLyricGame==='function'?(startLyricGame(m[1],m[2],!!m[3]),true):false;else{homeView();ok=true}if(ok){last=route;verify(route);return true}homeView();setTimeout(()=>run(route,true),60);return false}finally{routing=false}}
function enter(route){if(!route)return home();pendingBack=null;if(location.hash==='#'+route){if(owned(route))run(route,true);else fireLegacy();return true}location.hash=route;return true}
function home(){if(window.TinaGuard?.requestLeave&&!TinaGuard.requestLeave())return false;if(window.TinaGuard?.clearLeave)TinaGuard.clearLeave();history.replaceState({tinaHome:true},'',location.pathname+location.search);pendingBack=null;last='';homeView();return true}
function renderRoute(route){if(!route){last='';homeView();return}if(owned(route))run(route,true);else{normalizeSpecialist();fireLegacy()}verify(route)}
window.addEventListener('hashchange',e=>{const route=q();if(!owned(route)){normalizeSpecialist();verify(route);return}e.stopImmediatePropagation();run(route,true)},true);
window.addEventListener('popstate',()=>{const from=last||pendingBack;if(from&&gameVisible()&&q()!==from){pendingBack=from;const ok=!window.TinaGuard?.requestLeave||TinaGuard.requestLeave();if(!ok){history.pushState({tinaRoute:from},'','#'+from);pendingBack=null;renderRoute(from);return}if(window.TinaGuard?.clearLeave)TinaGuard.clearLeave();pendingBack=null;renderRoute(q());return}pendingBack=null;renderRoute(q())},true);
window.addEventListener('pageshow',e=>setTimeout(()=>renderRoute(q()),e.persisted?20:0));
window.TinaRouter={go:enter,home,render(){renderRoute(q());return true}};
window.addEventListener('load',()=>{ready=true;protectBack();const route=q();if(!route){history.replaceState({tinaHome:true},'',location.pathname+location.search);homeView()}else renderRoute(route)});
document.addEventListener('click',e=>{const target=e.target.closest('a[href^="#"],button');if(!target)return;let route='';if(target.matches('a[href^="#"]'))route=(target.getAttribute('href')||'').replace(/^#/,'');else{const oc=target.getAttribute('onclick')||'',m=oc.match(/location\.hash\s*=\s*['\"]([^'\"]+)/);if(m)route=m[1]}if(!route||target.closest('.back'))return;e.preventDefault();e.stopImmediatePropagation();enter(route)},true);
let reconcileTimer=0;new MutationObserver(()=>{protectBack();clearTimeout(reconcileTimer);reconcileTimer=setTimeout(()=>repair(q()),120)}).observe(document.getElementById('game'),{childList:true,subtree:true});
})();