(()=>{
let ready=false,routing=false,activeRoute='',guardArmed=false,leaving=false,repairTimer=0;
const q=()=>decodeURIComponent((location.hash||'').replace(/^#/,''));
const genericPK=/^pk-(countries|capitals|japan|us|china|aov|831|bestards|cosmos|samlee|fahrenheit|sasha)$/;
const territory=/^territory-(countries|japan|us|taiwan|china)-(area|population|density|gdp|military)$/;
function gameVisible(){const g=document.getElementById('game');return !!g&&getComputedStyle(g).display!=='none'}
function protectBack(){const top=document.querySelector('#game .top'),back=document.querySelector('#game .back');if(top){top.style.position='relative';top.style.zIndex='100';top.style.pointerEvents='auto'}if(back){back.style.position='relative';back.style.zIndex='101';back.style.pointerEvents='auto';back.style.touchAction='manipulation';back.style.minWidth='36px';back.style.minHeight='36px';back.style.display='flex';back.style.alignItems='center';back.style.justifyContent='center'}}
function homeView(){clearTimeout(repairTimer);if(typeof currentGame!=='undefined')currentGame=null;if(typeof resetUI==='function')resetUI();const h=document.getElementById('home'),g=document.getElementById('game');if(g)g.style.display='none';if(h){h.style.display='block';h.style.pointerEvents='auto'}document.body.style.pointerEvents='auto';protectBack()}
function gameView(){const h=document.getElementById('home'),g=document.getElementById('game');if(h)h.style.display='none';if(g)g.style.display='flex';protectBack()}
function markActive(route){activeRoute=route;window.TinaGuard?.markActive?.()}
function clearActive(){activeRoute='';guardArmed=false;window.TinaGuard?.clearLeave?.()}
function startRoute(route){if(!ready||routing)return false;routing=true;try{if(typeof currentGame!=='undefined')currentGame=route;if(typeof resetUI==='function')resetUI();gameView();let ok=true,m;if(['countries','capitals','japan','us','aov','831','bestards','cosmos','samlee','fahrenheit','sasha'].includes(route)){if(['fahrenheit','sasha'].includes(route)&&!(window.MUSIC_GAMES&&MUSIC_GAMES[route]))ok=false;else if(typeof start==='function')start(route);else ok=false}else if(route==='taiwan')ok=typeof startTaiwanSolo==='function'?(startTaiwanSolo(),true):false;else if(route==='china')ok=typeof startChina==='function'?(startChina(),true):false;else if(route==='price')ok=typeof startPriceSolo==='function'?(startPriceSolo(),true):false;else if(route==='pk-price')ok=typeof startPricePK==='function'?(startPricePK(),true):false;else if(route==='timeline')ok=typeof startTimelineSolo==='function'?(startTimelineSolo(),true):false;else if(route==='pk-timeline')ok=typeof startTimelinePK==='function'?(startTimelinePK(),true):false;else if(route==='pk-taiwan')ok=typeof startTaiwanPK==='function'?(startTaiwanPK(),true):false;else if(genericPK.test(route))ok=typeof startGenericPK==='function'?startGenericPK(route.slice(3)):false;else if((m=route.match(/^(831|bestards|cosmos|samlee|fahrenheit|sasha)-lyrics-(guess|fill)(-pk)?$/)))ok=typeof startLyricGame==='function'?(startLyricGame(m[1],m[2],!!m[3]),true):false;else if(territory.test(route)){ok='legacy'}else ok=false;if(ok===true){markActive(route);return true}if(ok==='legacy'){markActive(route);window.dispatchEvent(new HashChangeEvent('hashchange',{oldURL:location.href,newURL:location.href}));return true}homeView();return false}finally{routing=false}}
function renderCurrent(){const route=q();if(!route){clearActive();homeView();return true}return startRoute(route)}
function armHistoryGuard(route){if(!route||guardArmed)return;history.pushState({tinaGuard:true,route},'',location.pathname+location.search+'#'+route);guardArmed=true}
function go(route){if(!route)return home();if(activeRoute&&window.TinaGuard?.needsLeaveConfirm?.()){if(!window.TinaGuard.confirmLeave())return false;clearActive()}leaving=false;guardArmed=false;history.pushState({tinaRoute:true,route},'',location.pathname+location.search+'#'+route);const ok=startRoute(route);if(ok)armHistoryGuard(route);return ok}
function home(){if(activeRoute&&window.TinaGuard?.needsLeaveConfirm?.()&&!window.TinaGuard.confirmLeave())return false;clearActive();leaving=true;history.replaceState({tinaHome:true},'',location.pathname+location.search);homeView();setTimeout(()=>leaving=false,0);return true}
window.addEventListener('popstate',()=>{if(leaving)return;const route=q();if(activeRoute&&guardArmed&&route===activeRoute){guardArmed=false;if(window.TinaGuard?.needsLeaveConfirm?.()){if(!window.TinaGuard.confirmLeave()){armHistoryGuard(activeRoute);protectBack();return}window.TinaGuard.clearLeave?.()}const old=activeRoute;activeRoute='';leaving=true;history.back();setTimeout(()=>{leaving=false;if(q()===old){history.replaceState({tinaHome:true},'',location.pathname+location.search);homeView()}},80);return}clearActive();if(route)startRoute(route);else homeView()},true);
window.addEventListener('hashchange',e=>{if(leaving)return;const route=q();if(territory.test(route)){markActive(route);return}e.stopImmediatePropagation();if(activeRoute&&route===activeRoute)return;clearActive();if(route){startRoute(route);armHistoryGuard(route)}else homeView()},true);
window.addEventListener('pageshow',e=>setTimeout(()=>{if(leaving)return;const route=q();if(!route){clearActive();homeView();return}if(!activeRoute){startRoute(route);if(!history.state?.tinaGuard)armHistoryGuard(route)}},e.persisted?20:0));
window.TinaRouter={go,home,render:renderCurrent,get activeRoute(){return activeRoute}};
window.addEventListener('load',()=>{ready=true;protectBack();const route=q();if(!route){history.replaceState({tinaHome:true},'',location.pathname+location.search);homeView()}else{startRoute(route);if(!history.state?.tinaGuard)armHistoryGuard(route)}});
document.addEventListener('click',e=>{const back=e.target.closest('.back');if(back&&gameVisible()){e.preventDefault();e.stopImmediatePropagation();home();return}const target=e.target.closest('a[href^="#"],button');if(!target)return;let route='';if(target.matches('a[href^="#"]'))route=(target.getAttribute('href')||'').replace(/^#/,'');else{const oc=target.getAttribute('onclick')||'',m=oc.match(/location\.hash\s*=\s*['\"]([^'\"]+)/);if(m)route=m[1]}if(!route)return;e.preventDefault();e.stopImmediatePropagation();go(route)},true);
new MutationObserver(()=>protectBack()).observe(document.getElementById('game'),{childList:true,subtree:true});
})();