(()=>{
const JP_REGIONS={北海道:['01'],東北:['02','03','04','05','06','07'],關東:['08','09','10','11','12','13','14'],中部:['15','16','17','18','19','20','21','22','23'],近畿:['24','25','26','27','28','29','30'],中國:['31','32','33','34','35'],四國:['36','37','38','39'],九州沖繩:['40','41','42','43','44','45','46','47']};
const US_REGIONS={東北部:'ME,NH,VT,MA,RI,CT,NY,NJ,PA'.split(','),中西部:'OH,IN,IL,MI,WI,IA,KS,MN,MO,NE,ND,SD'.split(','),南部:'DE,FL,GA,MD,NC,SC,VA,WV,DC,AL,KY,MS,TN,AR,LA,OK,TX'.split(','),西部:'AZ,CO,ID,MT,NV,NM,UT,WY,AK,CA,HI,OR,WA'.split(',')};
function pct(a,b){return b?Math.round(a/b*100):0}
function collect(){const mode=(location.hash||'').slice(1),foundRegions=[...document.querySelectorAll('.region.found')].map(el=>el.__data__?.item).filter(Boolean);let title='',score=0,total=0,cats=[];
if(mode==='aov'){title='⚔️ 傳說對決英雄大挑戰';for(const [role,names] of Object.entries(AOV_GROUPS)){const hit=names.filter(name=>document.querySelector('.heroSlot.hit')&&[...document.querySelectorAll('.heroSlot.hit')].some(s=>s.textContent===name)).length;cats.push({name:role,hit,total:names.length})}score=cats.reduce((s,x)=>s+x.hit,0);total=AOV_HEROES.length}
else if(mode==='japan'){title='🗾 日本行政區大挑戰';const found=new Set(foundRegions.map(x=>x.code));for(const [name,codes] of Object.entries(JP_REGIONS))cats.push({name,hit:codes.filter(c=>found.has(c)).length,total:codes.length});score=found.size;total=JP.length}
else if(mode==='us'){title='🇺🇸 美國州大挑戰';const found=new Set(foundRegions.map(x=>x.abbr));for(const [name,codes] of Object.entries(US_REGIONS))cats.push({name,hit:codes.filter(c=>found.has(c)).length,total:codes.filter(c=>US.some(x=>x.abbr===c)).length});score=found.size;total=US.length}
else if(mode==='countries'){title='🌍 世界國家大挑戰';score=foundRegions.length;total=DATA.length}
else if(mode==='capitals'){title='🌎 世界首都大挑戰';score=foundRegions.length;total=DATA.length}
else return null;
const usable=cats.filter(x=>x.total>0),blind=usable.length?[...usable].sort((a,b)=>pct(a.hit,a.total)-pct(b.hit,b.total))[0]:null;return{mode,title,score,total,cats:usable,blind}}
function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function makeCard(r){const c=document.createElement('canvas');c.width=1080;c.height=1350;const x=c.getContext('2d');x.fillStyle='#f4f5f6';x.fillRect(0,0,c.width,c.height);x.fillStyle='#fff';rounded(x,55,55,970,1240,42);x.fillStyle='#20242a';x.font='700 38px -apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif';x.fillText('🎮 Tina遊戲櫃',105,135);x.fillStyle='#747b82';x.font='500 25px -apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif';x.fillText(r.title,105,190);x.fillStyle='#20242a';x.font='800 115px -apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif';x.fillText(String(r.score),105,345);x.font='600 42px -apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif';x.fillText('/ '+r.total,300,342);x.fillStyle='#667079';x.font='700 35px -apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif';x.fillText(pct(r.score,r.total)+'%',105,400);
let y=495;if(r.cats.length){x.fillStyle='#20242a';x.font='700 30px -apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif';x.fillText('分類統計',105,y);y+=58;for(const c1 of r.cats){x.fillStyle='#f1f3f4';rounded(x,105,y-31,850,48,18);x.fillStyle='#668396';const w=Math.max(6,850*(c1.hit/c1.total));rounded(x,105,y-31,w,48,18);x.fillStyle='#20242a';x.font='650 25px -apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif';x.fillText(c1.name,118,y+2);x.textAlign='right';x.fillText(c1.hit+'/'+c1.total+'  '+pct(c1.hit,c1.total)+'%',940,y+2);x.textAlign='left';y+=72}}
if(r.blind){y+=15;x.fillStyle='#f7f1e8';rounded(x,105,y-35,850,115,24);x.fillStyle='#6d5131';x.font='700 27px -apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif';x.fillText('🧠 記憶死角：'+r.blind.name,130,y+10);x.font='500 22px -apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif';x.fillText('只答出 '+r.blind.hit+'/'+r.blind.total+'（'+pct(r.blind.hit,r.blind.total)+'%）',130,y+50)}
x.fillStyle='#747b82';x.font='600 24px -apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif';x.fillText('你能贏過我嗎？',105,1215);x.font='500 20px -apple-system,BlinkMacSystemFont,"Noto Sans TC",sans-serif';x.fillText(location.origin,105,1255);return c}
async function share(r){const c=makeCard(r),blob=await new Promise(ok=>c.toBlob(ok,'image/png')),file=new File([blob],'tina-game-result.png',{type:'image/png'}),url=location.origin+'/#'+r.mode,text=`${r.title} 我答出 ${r.score}/${r.total}（${pct(r.score,r.total)}%）！你能贏過我嗎？`;
try{if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title:'Tina遊戲櫃',text,url,files:[file]});return}if(navigator.share){await navigator.share({title:'Tina遊戲櫃',text,url});return}}catch(e){if(e.name==='AbortError')return}
const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='tina-game-result.png';a.click()}
function install(){const r=collect();if(!r||document.querySelector('#shareResult'))return;const btn=document.createElement('button');btn.id='shareResult';btn.textContent='分享成績';btn.style.cssText='width:100%;margin-top:9px;height:44px;border:0;border-radius:10px;background:#20252b;color:#fff;font-weight:700;font-size:15px';btn.onclick=()=>share(collect());missing.appendChild(btn)}
finish.addEventListener('click',()=>setTimeout(install,60));window.addEventListener('hashchange',()=>document.querySelector('#shareResult')?.remove());
})();